### ISSUE TITLE
improve it..

### ISSUE THREAD

**Issue by designerfuzzi** [doomjs/dataview-getstring#1]
```js
.. post withdrawn to avoid hate speech.
```

**Comment by j-refs** [comment]
@designerfuzzi 
... I mean, you already fixed it... Why not just put in a pull request? Why make the dev do something you basically already did? Like I don't get it, you could have closed your own issue, but you expect someone who already made you free software to redo work you've already done? The dev is giving you value. You are taking value, so if anything, YOU should be the one to fix it, since YOU clearly got it figured out. 

That's just crazy, the entitlement...

**Comment by designerfuzzi** [comment]
how do you know i fixed it? Did you test it?

**Comment by designerfuzzi** [comment]
thanks for the rant.

**Comment by j-refs** [comment]
hey serious dude, if you did fix it, send em a merge please

**Comment by j-refs** [comment]
and also, if constructive criticism === hate speech for you, then im sorry, I really wish you the best
